### ISSUE TITLE
Setup script not working

### ISSUE THREAD

**Issue by utibeabasi6** [vmule/dotfiles#3]
![Screenshot 2023-08-05 at 4 03 17 PM](https://github.com/vmule/dotfiles/assets/66149718/584ca962-576b-410e-b137-31732116333e)

Hey, i ran the setup script now my terminal looks like this ☝🏾

**Comment by vmule** [comment]
Are you using iterm2?
You need to have the nerd font selected in iTerm.

**Comment by utibeabasi6** [comment]
![Screenshot 2023-08-06 at 2 11 12 AM](https://github.com/vmule/dotfiles/assets/66149718/f5ea550d-7449-4c83-a2b5-5743a3d4d04a)


Thanks changing the font worked. How can i change the color/theme for nvim? im not really familiar with it

**Comment by vmule** [comment]
This is where I set the color theme in my conf:
https://github.com/vmule/dotfiles/blob/d26bab716cec9e852c00181b28a39edf3c8e77dd/nvim/chadrc.lua#L20

you can also change it dynamically using LeaderKey + h + t 

Get yourself familiar with the base NvChad config https://github.com/NvChad/NvChad
my nvim setup is based on that
